
name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0,15,30,45 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: main
    - name: install chrome
      run: |
        sudo apt-get update
        sudo apt-get install chromium-chromedriver
        export PATH=$PATH:/usr/lib/chromium-browser/
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt          

    - name: Fetch latest data
      run: python program.py

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git status
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
